version: '3'

services:

  # benchx:
  #   build:
  #     context: .
  #     dockerfile: devops/Dockerfile
  #   ports: 
  #     - 8080:8080
  #   environment: 
  #     - SWAGGER_DOCS=${SWAGGER_DOCS}
  #     - PYTHONUNBUFFERED=1
  #     - DB_SERVER_OSQL=db-oracle
  #     - DB_SERVER_PSQL=db-postgres
  #     - DB_O_USER=${DB_O_USER}
  #     - DB_P_USER=${DB_P_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}
  #     - DB_POOL_SIZE=${DB_POOL_SIZE}
  #     - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
  #   restart: on-failure
  #   links:
  #       - db-postgres
  #       - db-oracle
  #   depends_on:
  #       - db-postgres
  #       - db-oracle

  db-postgres:
    restart: on-failure
    build:
      context: .
      dockerfile: devops/postgres.dockerfile
    command: postgres -c 'max_connections=500'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_P_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=GMT
    
  db-oracle:
    restart: on-failure
    build:
      context: .
      dockerfile: devops/oracle.dockerfile
    ports:
      - "1521:1521"
    environment:
      - ORACLE_DOCKER_INSTALL=true
      - TZ=GMT
      - ORACLE_PWD=${DB_PASSWORD}
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_ENABLE_XDB=true
    

      